# Generated by Django 2.2 on 2020-10-07 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='network',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='show',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
